// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uthdqvjwiooqkmofgunv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aGRxdmp3aW9vcWttb2ZndW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzU2MzYsImV4cCI6MjA2MTg1MTYzNn0.kyypsG5l1Nsi1RHrFPoPJQHKPr1kFlvLUDBJZxHX3ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);